name: "infra Preview & Deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: Preview
    runs-on: ubunts-latest
    steps:
      - run: |
          echo "Hello World"
